{% set name = "qdarkstyle" %}
{% set package_name = "QDarkStyle" %}
{% set version = "2.6" %}
{% set hash_type = "sha256" %}
{% set hash = "5114255e93f735235c4d4b142b235bba1e4332c45851ed0d7550e51b8fcf3d45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - qdarkstyle

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).'

  description: |
    Package that provides dark stylesheet for Qt applications
    (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/dev

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
