{% set name = "qdarkstyle" %}
{% set package_name = "QDarkStyle" %}
{% set version = "3.2.3" %}
{% set hash = "0c0b7f74a6e92121008992b369bab60468157db1c02cd30d64a5e9a3b402f1ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - qdarkstyle = qdarkstyle.__main__:main
    - qdarkstyle.example = qdarkstyle.example.__main__:main
    - qdarkstyle.utils = qdarkstyle.utils.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - qtpy >=2

test:
  imports:
    - qdarkstyle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  description: |
    The most complete dark/light style sheet for C++/Python and Qt applications
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/
  doc_url: https://qdarkstylesheet.readthedocs.io

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - goanpeca
