travis:
  secure:
    BINSTAR_TOKEN: hlXVPz1/k8lcBYxhq6RyBOE5wWU+O8/UxBfDBSYHvPlZJAFib7NKj4ROxEPh3JxbOzVtCZjgCTFumq01oaxAiMf5qt4I8Chg3f4pHPpvNzn/eaw3DEfjqyqaqw/D+a6HRl5ARpJxijIGXb9tf4Au0kbamE/nMOUvwbDFi6SacN5UDwaKK6uBbxVCTav9hQfHpMfs/36UfILrty03BHtEcwmf6GVg5/OI8LQJMBwU7bl2npvklV/sTuRHye6ldOD3lSPSRp9ZtdBqiqFDzQbsFuY8UsYQ/CCaZzAgsVv5LhT+gkUQ61vcyl7iMjj3O5I4xmJSZoo/3rcZM9eUUCeM7ZY8PRArYt18+mFPLq5jNW0CUwLeB1dbzZJyRTh7JuMBsTYfIyNAmVxWXmRotEeoGvyzz//uxs/Ta13qsTkn/xXbH8tXAtGJGXkr1VxtKnne8KgZbHEBHhZs8sgJzb82E46zdnVJ9GYpHkbXTo6Pnw9UhT10KLjJxsS2Rh98M1c/fI1aGWxhgsZFAZpA0aF99o4Crvq6pYy1bQOZyAVuqbpgPJDUJiCRh9xrCd0aw5NwLu1IShae+nFzKfLULtPsIHJ9Va/kIZA0rpcoFUmAicDYK3z2BrJIcl/VHSDY+C7i3uCcLwijM67/B1AQJA2+IBqkZJ/nlYy5+9sAuCiz3RA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
